name: teachable_machine_app
description: "Flutter app for Teachable Machine classification with accuracy tracking, history, and charts."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  tflite_flutter: ^0.12.1
  image: ^4.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  intl: ^0.18.1
  permission_handler: ^11.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/sensors/
    - assets/images/logo.png
    - assets/images/logo_2.png
    - assets/images/logo_3.png
    - assets/main_home_images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

